name: Linux Commands Demo

on:
  push:

jobs:
  linux-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Current Directory
        run: pwd

      - name: Show Logged-in User
        run: whoami

      - name: Show Current Date
        run: date

      - name: List Files
        run: ls -la

      - name: Print Message
        run: echo "Learning GitHub Actions with my buddy!"